Meal
grabiecpatrycja/omnomnom pull request #22
Opened 2024-08-20 14:18 UTC by grabiecpatrycja

2024-09-03 19:13 UTC, JerzySpendel requested changes

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/migrations/0003_alter_containermass_container_and_more.py
> +    ]
Please squash these migrations into one

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/models.py
>          return f"{self.container} - {self.mass}"
Add an empty line here, it's required by PEP8

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/models.py
> +    meals = [
Instead of this it's better to use the `django.db.models.TextChoices`

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/models.py
> +    meal = models.CharField(max_length=10, choices=meals, null=True, default=None)
If it's nullable its default value will always be `None`, you don't have to specify that

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/views.py
> +        meals = [choice[0] for choice in ContainerMass._meta.get_field('meal').choices]
Once you extract the `meal` attribute out of the model into the `Meal(TextChoices)` class, you will be able to do something like `meals = Meal.values` or even skip that variable and just use it directly in the loop definition

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/views.py
> +                        ContainerMass.objects.filter(container=o_container, date__date=date, meal=meal).order_by('-date').values('date')[:1]
😻

2024-09-03 19:13 UTC, JerzySpendel commented on backend/app_1/views.py
> +        results = []
A dictionary would be easier to use for the frontend, for example `results = {'D': ..., 'B': ...}`

2024-09-07 13:31 UTC, JerzySpendel commented on backend/app_1/models.py
> +    class MealChoices(models.TextChoices):
It's up to you, but you can also define this class outside `ContainerMass`. If it's defined inside, then the only way to access it is through `ContainerMass`

2024-09-07 13:31 UTC, JerzySpendel commented on backend/app_1/serializers.py
> +    meal = serializers.ChoiceField(choices=meals)
I think this:
```suggestion
    meal = serializers.ChoiceField(choices=ContainerMass.MealChoices.choices)
```
should work. Then you can remove the `meals` attribute above

2024-09-07 13:31 UTC, JerzySpendel commented on backend/app_1/models.py
>          return f"{self.container} - {self.mass}"
Still an empty line is there

2024-11-01 12:09 UTC, JerzySpendel requested changes

2024-11-01 12:09 UTC, JerzySpendel commented on backend/app_1/models.py
> +    class MealChoices(models.TextChoices):
Halo, was denkst du?

2024-12-03 16:08 UTC, grabiecpatrycja commented on backend/app_1/models.py
> +    class MealChoices(models.TextChoices):
I like it the way it is :)

2025-10-17 17:07 UTC, merged